SerpentIsaacGameAgentPlugin:
  frame_handler: PLAY
SerpentIsaacGamePlugin:
  fps: 2
SerpentPathofExileGamePlugin:
  fps: 2
SerpentSuperHexagonGameAgentPlugin:
  frame_handler: PLAY
SerpentSuperHexagonGamePlugin:
  fps: 2
SerpentTerrariaGamePlugin:
  fps: 2
